return {
  -- {
  --   'rmagatti/auto-session',
  --   lazy = false,
  --   dependencies = {
  --     'nvim-telescope/telescope.nvim', -- Only needed if you want to use sesssion lens
  --   },
  --   keys = {
  --     -- Will use Telescope if installed or a vim.ui.select picker otherwise
  --     { '<leader>wsl', '<cmd>SessionSearch<CR>', desc = '[W]orkspace [S]ession [L]ist' },
  --     { '<leader>wss', '<cmd>SessionSave<CR>', desc = '[W]orkspace [S]ession [S]ave' },
  --     { '<leader>wsa', '<cmd>SessionToggleAutoSave<CR>', desc = '[W]orkspace [S]ession [A]utosave' },
  --   },
  --   opts = {
  --     session_lens = {
  --       -- If load_on_setup is false, make sure you use `:SessionSearch` to open the picker as it will initialize everything first
  --       load_on_setup = true,
  --       theme_conf = { border = true },
  --       previewer = false,
  --       mappings = {
  --         -- Mode can be a string or a table, e.g. {"i", "n"} for both insert and normal mode
  --         delete_session = { 'i', '<C-D>' },
  --         alternate_session = { 'i', '<C-S>' },
  --       },
  --     },
  --     auto_session_suppress_dirs = {
  --       '/',
  --       '~/',
  --       '~/Projects',
  --       '~/Downloads',
  --       '~/data',
  --       '~/data/projects/',
  --     },
  --   },
  -- },
}
